package GrammaticalParser;

public enum StmtType {
    STMT, STMTBLOCK, TYPE, IFSTMT, WHILESTMT, BREAKSTMT, READSTMT, WRITESTMT,
    ASSIGNSTMT, EXPR, PROGRAM, VARIABLE, DECLARE,VARDEC,
    AddtiveExpr,Term,FACTOR, LOGICALOP, ADDOP, MULOP, VALUE,
    FORSTMT
}
